name: al_env
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - joblib=1.2.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.21
  - libsqlite=3.39.3
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - ncurses=6.3
  - numpy=1.23.3
  - openssl=3.0.5
  - pandas=1.5.0
  - pip=22.2.2
  - python=3.10.6
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2022.2.1
  - readline=8.1.2
  - scikit-learn=1.1.2
  - scipy=1.9.1
  - setuptools=65.3.0
  - six=1.16.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tzdata=2022c
  - wheel=0.37.1
  - xz=5.2.6
